# Generated by Django 5.1.1 on 2024-10-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('CDate', models.DateField(auto_now_add=True)),
                ('UDate', models.DateField(auto_now=True)),
                ('Name', models.CharField(max_length=50)),
                ('Text', models.TextField()),
                ('ImagePath', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('CDate', models.DateField(auto_now_add=True)),
                ('UDate', models.DateField(auto_now=True)),
                ('URLName', models.CharField(max_length=100, unique=True)),
                ('Title', models.CharField(max_length=100)),
                ('Text', models.TextField()),
                ('ShortText', models.CharField(max_length=5000)),
                ('AutorName', models.CharField(max_length=50)),
                ('ImagePath', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ShopArticle',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('CDate', models.DateField(auto_now_add=True)),
                ('UDate', models.DateField(auto_now=True)),
                ('Name', models.CharField(max_length=50)),
                ('Text', models.TextField()),
                ('ImagePath', models.CharField(max_length=120)),
                ('Price', models.FloatField()),
            ],
        ),
    ]
