# Generated by Django 5.1.1 on 2024-10-05 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoparticle',
            options={'verbose_name_plural': 'ShopArticles'},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='AutorName',
            new_name='AuthorName',
        ),
    ]
