# Generated by Django 5.1.1 on 2024-10-05 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_alter_shoparticle_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'AboutUs'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
    ]
