# Generated by Django 4.2.16 on 2024-10-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_alter_aboutus_options_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='AltImageText',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='ImagePath',
            field=models.CharField(default='no-image.jpg', max_length=120),
        ),
    ]
