# Generated by Django 4.2.15 on 2024-10-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_aboutus_altimagetext_alter_aboutus_imagepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='AltImageText',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shoparticle',
            name='AltImageText',
            field=models.CharField(default='', max_length=50),
        ),
    ]
